name: enelsis
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  flutter:
    sdk: flutter
  omni_datetime_picker: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
